version: '3'
services:
    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - 10080:80
        volumes:
          - ./nginx/logs:/var/log/nginx/
          - ./nginx/conf.d:/etc/nginx/conf.d
          - ./www:/www
        links:
          - php
    php:
        container_name: php
        build: build/php
#        ports:
#            - 19000:9000
        volumes:
          - ./php/conf.d:/usr/local/etc/php/conf.d
          - ./www:/www
        links:
            - redis
    redis:
        container_name: redis
        # 指定镜像
        image: redis:latest
        ports:
            - 16379:6379
        volumes:
            - ./data/redis/data:/data
        command:
            redis-server
    mysql:
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "1q2w3e4r"
            MYSQL_USER: 'root'
            MYSQL_PASS: '1q2w3e4r'
        image: mysql:5.7
        restart: always
        volumes:
            - ./data/mysql/data:/var/lib/mysql
        ports:
            - 13306:3306
