version: '2'
services:
    nginx:
        container_name: nginx
        image: nginx:stable
        restart: always
        ports:
            - 80:80
        volumes:
          - ./nginx/logs:/var/log/nginx/
          - ./nginx/conf.d:/etc/nginx/conf.d
          - /data/www:/var/www/html
        links:
          - php
    php:
        container_name: php
        build: build/php/7.4
        ports:
            - 9501:9501
        volumes:
          - /data/www:/var/www/html
          - ./addon/supervisord.d/:/etc/supervisor/conf.d/
          - ./addon/php/swoole.ini:/usr/local/etc/php/conf.d/swoole.ini
          - ./addon/php/php.ini:/usr/local/etc/php/php.ini
          - ./addon/bash/run.sh:/opt/run.sh
        command: /opt/run.sh

        links:
            - redis
    redis:
        container_name: redis
        # 指定镜像
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        volumes:
            - /data/lnmp/redis/data:/data
        command:
            redis-server
    mysql:
        container_name: mysql
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "1q2w3e4r"
            MYSQL_USER: 'root'
            MYSQL_PASS: '1q2w3e4r'
        volumes:
            - /data/lnmp/mysql/data:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "1q2w3e4r"
            MYSQL_ROOT_PASSWORD: "1q2w3e4r"
            PMA_HOST: mysql
            PMA_USER: "root"
            PMA_PASSWORD: "1q2w3e4r"
